apiVersion: batch/v1
kind: Job
metadata:
  name: hello-kubernetes-db-migrate
spec:
  template:
    metadata:
      name: hello-kubernete-db-migrate
    spec:
      containers:
      - name: hello-kubernetes-migrate
        image: gcr.io/${PROJECT_ID}/hello-kubernetes:${COMMIT_SHA}
        imagePullPolicy: Always
        command: ["/bin/sh", "-c"]
        args:
          - |
            trap "touch /tmp/pod/main-terminated" EXIT
            bundle exec rake db:create db:migrate
        volumeMounts:
          - mountPath: /tmp/pod
            name: tmp-pod
        env:
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: cloudsql-db-credentials
              key: username
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: cloudsql-db-credentials
              key: password
        - name: DB_HOST
          value: localhost
        - name: DB_PORT
          value: "3306"
        - name: DB_DBNAME
          value: "hello_kubernetes_production"
        - name: SECRET_KEY_BASE
          value: "88d24294e8de572f8526f0f0fcc51c0a857b58aee01182303c8bed8fae8646831a350f323e1d090c43055e6466275500006bc312ea0ab287cc0cb611619666fb"
      - name: cloudsql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:1.11
        command: ["/bin/sh", "-c"]
        args:
          - |
            /cloud_sql_proxy --dir=/cloudsql -instances=${CONNECTION_NAME}=tcp:3306 -credential_file=/secrets/cloudsql/credentials.json &
            CHILD_PID=$!
            (while true; do if [[ -f "/tmp/pod/main-terminated" ]]; then kill $CHILD_PID; echo "Killed $CHILD_PID as the main container terminated."; fi; sleep 1; done) &
            wait $CHILD_PID
            if [[ -f "/tmp/pod/main-terminated" ]]; then exit 0; echo "Job completed. Exiting..."; fi
        volumeMounts:
          - name: cloudsql-instance-credentials
            mountPath: /secrets/cloudsql
            readOnly: true
          - name: cloudsql
            mountPath: /cloudsql
          - mountPath: /tmp/pod
            name: tmp-pod
            readOnly: true
      restartPolicy: Never
      volumes:
      - name: cloudsql-instance-credentials
        secret:
          secretName: cloudsql-instance-credentials
      - name: cloudsql
        emptyDir:
      - name: tmp-pod
        emptyDir: {}
  backoffLimit: 1
