AllCops:
  Exclude:
    - db/**
    - node_modules/**/*
    - vendor/**/*
    - bin/**/*
  TargetRubyVersion: 2.5.1

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
