steps:
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'sh'
  args:
    - '-c'
    - |
      docker pull gcr.io/$GC_PROJECT/$GC_IMAGE:latest || true
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--cache-from', 'gcr.io/$GC_PROJECT/$GC_IMAGE:latest', '-t', 'gcr.io/$GC_PROJECT/$GC_IMAGE:latest', '-t', 'gcr.io/$GC_PROJECT/$GC_IMAGE:$COMMIT_SHA', '.' ]
images:
- 'gcr.io/$GC_PROJECT/$GC_IMAGE:latest'
- 'gcr.io/$GC_PROJECT/$GC_IMAGE:$COMMIT_SHA'
timeout: 3600s
