steps:
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'sh'
  args:
    - '-c'
    - |
      docker pull gcr.io/${PROJECT_ID}/hello-kubernetes:latest || true
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--cache-from', 'gcr.io/${PROJECT_ID}/hello-kubernetes:latest', '-t', 'gcr.io/${PROJECT_ID}/hello-kubernetes:latest', '-t', 'gcr.io/${PROJECT_ID}/hello-kubernetes:${COMMIT_SHA}', '.' ]
images:
- 'gcr.io/${PROJECT_ID}/hello-kubernetes:latest'
- 'gcr.io/${PROJECT_ID}/hello-kubernetes:${COMMIT_SHA}'
timeout: 3600s
