steps:
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'sh'
  args:
    - '-c'
    - |
      docker pull gcr.io/${PROJECT_ID}/${_GC_IMAGE}:latest || true
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--cache-from', 'gcr.io/${PROJECT_ID}/${_GC_IMAGE}:latest', '-t', 'gcr.io/${PROJECT_ID}/${_GC_IMAGE}:latest', '-t', 'gcr.io/${PROJECT_ID}/${_GC_IMAGE}:${COMMIT_SHA}', '.' ]
images:
- 'gcr.io/${PROJECT_ID}/${_GC_IMAGE}:latest'
- 'gcr.io/${PROJECT_ID}/${_GC_IMAGE}:${COMMIT_SHA}'
timeout: 3600s
